version: '3.3'
services:
   db:
     image: mysql
     volumes:
       - C:\Users\a843877\Documents\MYSQl:/var/lib/mysql/
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Password
     ports:
       - "3307:3306"
     container_name: mysql
